GRAVITY = -1.5
GRAVITY_JUMP_CONTINUOUS = GRAVITY_CAP_JUMP = JUMP_ACCEL_BACKWARDS = -1
GRAVITY_CAP_THROW = -0.3
SPEED_CAP_THROW = 5.7
GRAVITY_CAP_THROW_FRAME = 23
SPEED_CAP_JUMP_H = 16
SPEED_CAP_JUMP_V = 21
SPEED_DIVE_H = 20
SPEED_DIVE_V = 26
GRAVITY_DIVE = -2
SPEED_CAP_THROW_LIMIT = 7
TERMINAL_V = -35
JUMP_ACCEL_FORWARDS = 0.5
JUMP_ACCEL_SIDE = 0.3
